version: '3.9'
services:
  # hair_services postgresql db
  hair_services_db:
    container_name: hair_services_db
    image: postgres:15.3-bullseye
    env_file:
      - .env
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
    ports:
      - "${SERVER_POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - hairsol_db_data:/var/lib/postgresql/data
    command: postgres -c max_connections=300
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -h localhost -p 5432 -U abiorh -d hair_services_db"]
      interval: 60s
      timeout: 30s
      retries: 3
    labels:
      - "com.docker.compose.services.hair_services_db.healthcheck.status=/health"
    
      
  # hair_services django server
  hair_services:
    container_name: hair_services_server
    build: .
    env_file:
      - .env
    environment:
      - SECRET_KEY
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
      - AWS_S3_BUCKET_REGION_NAME
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - CELERY_BROKER_URL
      - IPSTACK_API_KEY
      - CUSTOM_GOOGLE_APPLICATION_CREDENTIALS
      - BRAINTREE_MERCHANT_ID
      - BRAINTREE_PUBLIC_KEY
      - BRAINTREE_PRIVATE_KEY
    ports:
      - "${HAIRSERVICES_SERVER_PORT}:${HAIRSERVICES_SERVER_PORT}"
    volumes:
      - .:/hair_services_backend
    command: /hair_services_backend/docker_scripts/django_application_server/docker-entrypoint.sh
    depends_on:
      - hair_services_db
    restart: always
      
  # hair_services redis server
  hair_services_redis:
    container_name: hair_services_redis
    image: redis:7.2.3-alpine
    ports:
      - "${SERVER_REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - hair_services_redis_data:/data
    command: redis-server --appendonly yes
    restart: always
  
  # hair_services celery worker
  hair_services_celery_worker:
    container_name: hair_services_celery_worker
    build: .
    env_file:
      - .env
    environment:
      - SECRET_KEY
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
      - AWS_S3_BUCKET_REGION_NAME
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - CELERY_BROKER_URL
      - IPSTACK_API_KEY
      - CUSTOM_GOOGLE_APPLICATION_CREDENTIALS
      - BRAINTREE_MERCHANT_ID
      - BRAINTREE_PUBLIC_KEY
      - BRAINTREE_PRIVATE_KEY
    volumes:
      - .:/hair_services_backend
    command: celery -A hair_services worker -l info
    depends_on:
      - hair_services_redis
      - hair_services
    restart: always
  
  # hair_services nginx web server
  hair_services_nginx:
    container_name: hair_services_nginx_web_server
    build: .
    command: /hair_services_backend/docker_scripts/nginx_web_server/docker-entrypoint.sh
    ports:
      - "${SERVER_NGINX_PORT}:${NGINX_PORT}"
      - "${SERVER_NGINX_SSL_PORT}:${NGINX_SSL_PORT}"
    depends_on:
      - hair_services
    restart: always
    

# volumes
volumes:
  hair_services_db_data
  hair_services_redis_data
