# Generated by Django 4.1.7 on 2023-12-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('on-waiting', 'On Waiting'), ('on-process', 'On Process'), ('finished', 'Finished')], default='booked', max_length=20),
        ),
    ]
