# Generated by Django 4.1.7 on 2023-12-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_booking', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
