# Generated by Django 4.1.7 on 2023-12-06 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('professional_service_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovideravailability',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='service_provider_services', to='services.service'),
        ),
        migrations.AddField(
            model_name='serviceprovideravailability',
            name='service_provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='professional_service_provider.serviceproviderprofile'),
        ),
    ]
