# Generated by Django 4.1.7 on 2023-12-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('professional_service_provider', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovideravailability',
            name='service',
        ),
        migrations.AddField(
            model_name='serviceprovideravailability',
            name='service',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
            preserve_default=False,
        ),
    ]
