# Generated by Django 4.1.7 on 2023-12-11 07:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional_service_provider', '0003_remove_serviceprovideravailability_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovideravailabledate',
            name='available_times',
        ),
        migrations.AddField(
            model_name='serviceprovideravailability',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='serviceprovideravailability',
            name='end_time',
            field=models.TimeField(default='23:59:59'),
        ),
        migrations.AddField(
            model_name='serviceprovideravailability',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='serviceprovideravailability',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional_service_provider.serviceproviderprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceprovideravailability',
            unique_together={('service_provider', 'date', 'start_time', 'end_time')},
        ),
        migrations.DeleteModel(
            name='ServiceProviderAvailableTime',
        ),
        migrations.RemoveField(
            model_name='serviceprovideravailability',
            name='available_dates',
        ),
        migrations.RemoveField(
            model_name='serviceprovideravailability',
            name='service',
        ),
        migrations.DeleteModel(
            name='ServiceProviderAvailableDate',
        ),
    ]
