# Generated by Django 4.1.7 on 2023-12-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='service_category_picture',
            field=models.ImageField(blank=True, null=True, upload_to='service_category_pictures/'),
        ),
    ]
